# Generated by Django 5.2.5 on 2025-09-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagens',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='viagens',
            name='instructions',
        ),
    ]
