# Generated by Django 5.2.5 on 2025-08-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_viagem_delete_viagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viagem',
            old_name='imgage',
            new_name='image',
        ),
    ]
